In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Base de vendas
dados_vendas = {
    'cliente_id': [101, 102, 103, 101, 104, 102, 105, 103],
    'valor': [3500.75, 189.50, np.nan, 1200.00, 450.00, np.nan, 89.90, 780.50],
    'categoria': [
        'Eletronicos',
        'Livros',
        'Roupas',
        'Eletronicos',
        'Automotivo',
        'Livros',
        'Roupas',
        'Roupas',
    ],
    'data_hora': [
        '2024-01-15 10:23:00',
        '2024-01-18 14:05:00',
        '2024-02-05 09:12:00',
        '2024-02-20 16:40:00',
        '2024-03-02 11:00:00',
        '2024-03-15 18:30:00',
        '2024-04-10 08:20:00',
        '2024-04-22 13:45:00',
    ],
    'status': [
        'Concluído',
        'Concluído',
        'Pendente',
        'Concluído',
        'Cancelado',
        'Concluído',
        'Concluído',
        'Concluído',
    ],
    'email': [
        'maria@gmail.com',
        'joao@outlook.com',
        'ana@yahoo.com',
        'maria@gmail.com',
        'carlos@gmail.com',
        'joao@outlook.com',
        'lucas@empresa.com.br',
        'ana@yahoo.com',
    ],
}

# Base de clientes
dados_clientes = {
    'cliente_id': [101, 102, 103, 104, 105],
    'nome': [
        'Maria Silva',
        'Joao Souza',
        'Ana Oliveira',
        'Carlos Lima',
        'Lucas Mendes',
    ],
    'cidade': [
        'Sao Paulo',
        'Rio de Janeiro',
        'Belo Horizonte',
        'Curitiba',
        'Salvador',
    ],
}

df_vendas = pd.DataFrame(dados_vendas)
df_clientes = pd.DataFrame(dados_clientes)

#Parte 1: Diagnóstico e Limpeza (Básico)

1. Inspecione as dimensões e o resumo dos tipos de dados do DataFrame df_vendas usando .shape e .info().

In [ ]:
df_vendas.shape

(8, 6)

In [ ]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  8 non-null      int64
 1   valor       8 non-null      float64
 2   categoria   8 non-null      object
 3   data_hora   8 non-null      object
 4   status      8 non-null      object
 5   email       8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

2. Identifique os valores nulos e preencha os registros ausentes da coluna valor utilizando a mediana da respectiva categoria ou a mediana global com .fillna().

In [ ]:
df_vendas['valor'] = df_vendas['valor'].fillna(df_vendas['valor'].median())
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  8 non-null      int64
 1   valor       8 non-null      float64
 2   categoria   8 non-null      object
 3   data_hora   8 non-null      object
 4   status      8 non-null      object
 5   email       8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

3. Filtre e exiba apenas as transações com status 'Concluído' e valor superior a R$ 500,00 usando .loc[] ou .query().

In [ ]:
df_vendas.loc[(df_vendas['status'] == 'Concluído') & (df_vendas['valor'] > 500.0)]

,cliente_id,valor,categoria,data_hora,status,email
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com
5,102,615.25,Livros,2024-03-15 18:30:00,Concluído,joao@outlook.com
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com

#Parte 2: Cruzamento e Transformação (Intermediário)

4. Realize uma junção relacional (left merge) entre df_vendas e df_clientes utilizando a chave cliente_id

In [ ]:
df_completo = pd.merge(df_vendas, df_clientes, on='cliente_id', how='left')
display(df_completo)

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
2,103,615.25,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba
5,102,615.25,Livros,2024-03-15 18:30:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
6,105,89.90,Roupas,2024-04-10 08:20:00,Concluído,lucas@empresa.com.br,Lucas Mendes,Salvador
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com,Ana Oliveira,Belo Horizonte

5. Crie uma nova coluna chamada media_categoria contendo o valor médio de vendas por categoria sem reduzir o número de linhas do DataFrame (utilize .groupby() com .transform()).

In [ ]:
df_completo['media_categoria'] = df_completo.groupby('categoria')['valor'].transform('mean')
df_completo.head(5)

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade,media_categoria
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375000
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro,402.375000
2,103,615.25,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte,495.216667
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375000
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba,450.000000

6. Identifique quantos clientes usam o provedor de e-mail @gmail.com através do acessor de texto .str.contains()

In [ ]:
df_completo.loc[df_completo['email'].str.contains('@gmail.com')]

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade,media_categoria
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba,450.000

#Parte 3: Análise Temporal e Agregação (Intermediário)

7. Converta a coluna data_hora para o tipo datetime nativo com pd.to_datetime() e extraia o mês por extenso ou o nome do dia da semana utilizando o acessor .dt

In [ ]:
df_completo['data_hora'] = pd.to_datetime(df_completo['data_hora'], format='%Y-%m-%d %H:%M:%S')
df_completo['mes_extenso'] = df_completo['data_hora'].dt.month_name()
display(df_completo[['data_hora', 'mes_extenso']].head())

            data_hora mes_extenso
0 2024-01-15 10:23:00     January
1 2024-01-18 14:05:00     January
2 2024-02-05 09:12:00    February
3 2024-02-20 16:40:00    February
4 2024-03-02 11:00:00       March

8. Construa uma tabela dinâmica com pd.pivot_table() apresentando o total (sum) do valor de vendas agrupado por categoria nas linhas e por cidade nas colunas, preenchendo eventuais valores nulos com zero.

In [ ]:
pd.pivot_table(df_completo, values='valor', index='categoria', columns='cidade', aggfunc='sum').fillna(0)

cidade       Belo Horizonte  Curitiba  Rio de Janeiro  Salvador  Sao Paulo
categoria
Automotivo             0.00     450.0            0.00       0.0       0.00
Eletronicos            0.00       0.0            0.00       0.0    4700.75
Livros                 0.00       0.0          804.75       0.0       0.00
Roupas              1395.75       0.0            0.00      89.9       0.00